### ISSUE TITLE
SeeSwap - add the information how much liquidity the user has to exit pool function

### ISSUE THREAD

**Issue by BrunoMarshall** [kuyawa/seeswap#1]
When the user want to exit a pool is important to know how much was added previously to the respective pool.

--> **Currently**: is not shown any value

--> **Proposal:** add information how much tokens the user has able to remove

 
![image](https://user-images.githubusercontent.com/35432495/95688437-6940e900-0c0a-11eb-926c-8d6e35c26a00.png)

**Comment by kuyawa** [comment]
Balance and liquidity info is now shown
