### ISSUE TITLE
Show amount of ONE Tokens

### ISSUE THREAD

**Issue by yelllowsin** [kuyawa/seeswap#2]
Would be nice to show the amount the ONE Wallet has once you connect it. This will help the user know which wallet he is connected with and monitor the ONE Balance without having to go back to the extension for that. Maybe put the balance where the Dark mode button is and move this last one to the right?

Uniswap has this same feature for ETH: https://app.uniswap.org/

![image](https://user-images.githubusercontent.com/7217595/95894591-af5b9100-0d5f-11eb-897b-303e91688729.png)

**Comment by kuyawa** [comment]
Wallet balance now shown
